services:
  express:
    build:
      args:
        - port=${PORT}
      context: express/
    ports:
      - 5000:${PORT}
    env_file:
      - .env
      - .env.local
  nginx:
    build: nginx/
    ports:
    - 80:80