services:
  express:
    build:
      args:
        - port=${PORT}
      context: express/
    ports:
      - 5000:${PORT}
    env_file:
      - .env
      - .env.local
  nginx:
    image: nginx:alpine
    ports:
    - 80:80
    - 443:443
    volumes:
      - ${HOME}/letsencrypt:/data/letsencrypt
      - ./conf.d:/etc/nginx/conf.d
      - ./start-nginx.sh:/start-nginx.sh
    entrypoint: ./start-nginx.sh
    env_file:
      - .env
      - .env.local